print ("##############################")
print ("#                            #")
print ("#    Ikhtiara Fakhrunisa     #")
print ("#       2210817120003        #")
print ("#                            #")
print ("##############################")